; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
lib_deps = pololu/QTRSensors@^4.0.0
monitor_speed = 115200
monitor_filters = send_on_enter
monitor_echo = yes

[env:version_1]
build_src_filter = 
    +<*> 
    -<V2/>

[env:version_2]
build_src_filter = 
    +<*> 
    -<V1/>
